<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    const DEFAULT_PASSWORD = 'bubt1234';
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            // ADVISORY
            [
                'name' => 'Dr. Md. Fayyaz Khan',
                'email' => 'fayaaz@mail.com',
                "designation" => "Vice Chancellor",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                'type' => \App\Enums\UserType::ADVISORY,
                'password' => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                'name' => 'Md Saifur Rahman',
                'email' => 'saifurs@gmail.com',
                "designation" => "Vice Chancellor",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                'type' => \App\Enums\UserType::ADVISORY,
                'password' => bcrypt(self::DEFAULT_PASSWORD),
            ],

            // Executive Member
            [
                "name" => "Abu Hena Md Sahin",
//                "mobile" => "01717017565",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "shahin1997@gmail.com",
                "designation" => "President",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Nazmul Islam Bhuiyan",
//                "mobile" => "01711452647",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "nibcse@gmail.com",
                "designation" => "Vice President",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Alim Al Razi",
//                "mobile" => "01787667167",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "alrazi17@gmail.com",
                "designation" => "Vice President",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mehedi Hasan Nahid",
//                "mobile" => "01700743854",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "nahid.dns@gmail.com",
                "designation" => "General Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
 /*           [
                "name" => "Ali Sazzad Sohag",
//                "mobile" => "01671591543",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "Joint Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],*/
            [
                "name" => "Moudud Hasan",
//                "mobile" => "01786273127",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "moududhasanbubt@gmail.com",
                "designation" => "Joint Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Hafizul Alam",
//                "mobile" => "01673338948",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "hafizulalam11@gmail.com",
                "designation" => "Treasurer",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mahamudul Karim Mazumder",
//                "mobile" => "01670167395",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "makreza6@gmail.com",
                "designation" => "Organization Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Faiz Ahamed Shipu",
//                "mobile" => "01616022669",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "shipuahamed01@gmail.com",
                "designation" => "Joint Organization Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Ahasanul Alam Rifat",
//                "mobile" => "01740592693",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "ahasanulalamrifat@gmail.com",
                "designation" => "Joint Organization Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Ashraful Islam",
//                "mobile" => "01723777711",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "ashraful@bubt.edu.bd",
                "designation" => "Research Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Taposhi Rabea",
//                "mobile" => "01681398858",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "taposhi@gmail.com",
                "designation" => "It, Publication and Media Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Foysal Zafree",
//                "mobile" => "01771443388",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "foysalzafree@gmail.com",
                "designation" => "Cultural Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mohammad Mehedi Hasan",
//                "mobile" => "01754242590",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "hasanbdmehadi@gmail.com",
                "designation" => "Office Secretary",
                "type" => \App\Enums\UserType::EXECUTIVE,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],

            // General member
            [
                "name" => "Mehedi Hasan Akash",
//                "mobile" => "01521456159",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "mehaakmehi@gmail.com",
                "designation" => "Office Secretary",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mufti Muntasir",
//                "mobile" => "01754242590",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "hasanbdmehadi2@gmail.com",
                "designation" => "Office Secretary",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],

            [
                "name" => "Md. Abu Sufian",
//                "mobile" => "01515629767",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "sufiantipu@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::MEMBER,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Tushar Roy",
//                "mobile" => "01610143420",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "tushar.roy.cse@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "M.H. Numan",
//                "mobile" => "01827211193",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "mahmudnuman@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Tariqul Islam",
//                "mobile" => "01917272349",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "tariqul4911@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Abu Rayhan Ahmad",
//                "mobile" => "01965691244",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "rayhan.ahmed5000@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Kaniz Fatema Mow",
//                "mobile" => "01627957677",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "samiyamow613@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Golam Mahbub Fahad",
//                "mobile" => "01684326463",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "mahbub.fahad@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Avishekh Bhowmik",
//                "mobile" => "01521487199",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "email" => "avishekh.bhowmik71@gmail.com",
                "designation" => "General Members",
                "type" => \App\Enums\UserType::GENERAL,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],


            // new added
            [
                "name" => "Mahedi Imam",
                "email" => "imammahedi76@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Senior Engineer, Product & Technology",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Iftekhar Ahmed Eather",
                "email" => "eather.ahmed@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "System Engineer and Sub Leader",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md.Mehedi Hasan",
                "email" => "mehedi.edu0@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jr.iOS Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Shipra Rani Sarkar",
                "email" => "shipra.sarkar@quantanite.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Data Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sharif Hossain",
                "email" => "md.shorif01762@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT Support Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Saddam Hossain",
                "email" => "saddambubt65@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Assistant Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Kaiser Ahmed Tushar",
                "email" => "tusharkaiser@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Technical Team Lead",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Solaiman shohag",
                "email" => "wdxshohag@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Suvradeb Biswas",
                "email" => "suvradeb88@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Support Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Chowdhury Sudip Deb Nath",
                "email" => "bubtsudip@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Assistant Network Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Mahbubur Rahman",
                "email" => "mahbubmridha07@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Manager ( Lead App Development Team)",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Shariful Islam",
                "email" => "shariful.cse.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Forhad Hossain",
                "email" => "forhad2097@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "SQA Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Tasnem Meem",
                "email" => "tasnemmeem114@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Product specialist",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Naim Ahammed",
                "email" => "naimahammed.uc.my@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Deputy Manager",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Ashraful Alam",
                "email" => "emonak52@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer ( Custom Business Software Solutions )",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Saifullah Tarique",
                "email" => "saifullahtarique9@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Online Sales Manager",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sabbir Ahmed",
                "email" => "sabbirahmedesi@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "System Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Shohag Ali Sarder",
                "email" => "shohagsb@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jr. Execute IT",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Abu Saim",
                "email" => "abusaim1994@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Lead Web Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Elias Hassan Naim",
                "email" => "naimelias56@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Associate Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Emran Khan",
                "email" => "emran19282@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Maneger In Charge",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Tahsin hossen",
                "email" => "Tahsinhossen3@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "No",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Anika Tabassum Medha",
                "email" => "anikamedha97@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Solution delivery executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "G.M. Shoaibuzzaman",
                "email" => "shoaib.zaaman@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Suma Rani Sarker",
                "email" => "s.ranisarker@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Instructor",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Rafa mir",
                "email" => "420rafamir@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Teacher",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Rackibur Rahman",
                "email" => "rackibur.rahman@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Data artist Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Naimur Rahman",
                "email" => "naimbubt15@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Fahad Ahammed",
                "email" => "fahadbubt85@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Web Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Avishek Bhowmik",
                "email" => "avishek.bhowmik71@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Associate",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Tawkir Hossain Ratul",
                "email" => "tawkirh@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Sakibul Islam",
                "email" => "sakibul95bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "MD Nazmul Alam",
                "email" => "nazmulpcc@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mahtab Khandaker Bishal",
                "email" => "mahtab3310@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "ABU RAYHAN MIAH",
                "email" => "miahaburayhan@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Assistant Programmer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Nahid Hasan Limon",
                "email" => "nh.limon2010@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Rafiqul Islam Rafi",
                "email" => "rafiqul.abprs@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Masrur Riasat",
                "email" => "masrurriasat@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Operation executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "MD. ALIF",
                "email" => "alifkhan.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "New seller",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Rakib Mahmud Hridoy",
                "email" => "rakibmahmud2607@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Intern",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Hasibul Ahsan",
                "email" => "hasibalhasan20@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "SEO & Digital Marketing Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Susmita debnath",
                "email" => "susmitadab@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "It executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Samia Sultana Pushpo",
                "email" => "pushpo.cse@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Android Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Rajia Sultana",
                "email" => "prityakter01980@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Computer Teacher",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Masud Rana Basunia",
                "email" => "masud.rana.bubt.id193@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Shorif Uddin Al Mahamud",
                "email" => "almahamud.shorifuddin@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "System Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "S.M. Akash",
                "email" => "smakash.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Assistant Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Motiur Rahman",
                "email" => "bubt.mrahman1996@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mahadi Hasan Rabby",
                "email" => "mahadi.hassan.rabby32@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT system engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "ANANNA ALOM CHOWDHURY GITI",
                "email" => "gitielham20@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Operational Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sayeef t",
                "email" => "sayeef.cse@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Digital Marketing Specialist",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Shahin Khan",
                "email" => "shahinshanto.cse@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Lecturer & Coordinator",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Azrin Nahar Anika",
                "email" => "azrin.nahar308@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Associate Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Emam Hossen Sohag",
                "email" => "cmtshohag@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jn. Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Umme Hafcha Mukti",
                "email" => "hafchamukti.cse30@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Teaching Assistant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Fatema Tuz Zohra",
                "email" => "ftz.bristy93@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Sr. Executive - Digital Marketing",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Safayet Hossain",
                "email" => "safayetbubt111@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Web Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Nazrul Islam",
                "email" => "nazrul.islam8495@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Web Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md.Abu. Raihan (Niloy)",
                "email" => "niloy.cse69@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Assistant teacher",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Shaikh Rubayat Hossen",
                "email" => "rubayat0007@icloud.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Mezanur Rahman Maruf",
                "email" => "maruf.cse.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Network Security Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Habibur Rahman",
                "email" => "habibcse1@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jr. Asst. Manager (Technical)",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Avrojit Das",
                "email" => "avrojit.cse.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Customer Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Syeada Shakila Akram",
                "email" => "Syeadashakilaakram@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Solution Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mahadi Hassan",
                "email" => "mh@mahadihassan.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Aminul Islam",
                "email" => "apo_n05@yahoo.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Officer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Mizanur Rahman",
                "email" => "mahinmjm@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT Assistant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Abu Nesar Shahin",
                "email" => "abunesar87@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sunil Chandra Karmakar",
                "email" => "sunil_karmakar@ymail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "MD ARIFUL ISLAM",
                "email" => "mdariful77@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT -Assistant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "A.M. Shahabuddin Ahmed",
                "email" => "sashahabuddin@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "It Mnager",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Sazzadul Islam",
                "email" => "sazzadulislam6@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Senior Software Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sheikh Md Mahamudur Rahaman",
                "email" => "mrprotik61@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Studio Manager",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Adnan Biswas",
                "email" => "adnanrabby2@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Data Analysis",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Anisur Rahman Tonu",
                "email" => "tonububt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "M M Mehedi Hasan",
                "email" => "mehedi.self@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer (IOS)",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Nazmul Hasan Rabby",
                "email" => "nazmul@pinesolutions.xyz",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Tech Consultant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sheikh Rafid Reza",
                "email" => "rafid.reza.nabil@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "UI/UX Designer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Dipu Akter Shila",
                "email" => "dipu.cse.bubt97@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Teaching Assistant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Abu Quwsar Ohi",
                "email" => "quwsarohi@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Research Assistant",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mohammad Hasibul Hossaim",
                "email" => "hasibhosen7612@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sifat-Nur-Billah",
                "email" => "sifat3198@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Soc Analyst",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Yasin Khan",
                "email" => "khanyeasin44@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Jalilur Rahman",
                "email" => "jalilcse03@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Rayhan Al Shorif",
                "email" => "rayhanalshorif@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Student of BUBT",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Tanvir Ahmed",
                "email" => "tanvirahmed.cse.bubt@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mohammad Wahid",
                "email" => "mohammadwahid349@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Fuad Hasan Emon",
                "email" => "fuadhasanemon8@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Web Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Arika Afrin Boshra",
                "email" => "arika.afrin@bubt.edu.bd",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Associate Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "MD. AL-MAHMUD",
                "email" => "al.mahmud00777@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jr. Backend Software Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Naziba Hasan Talukder",
                "email" => "naziba@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Home",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Hasan Ali",
                "email" => "hasan.bubt.40@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Programmer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md.Rakibul Islam",
                "email" => "rakibulislamrakib216@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "IT Executive",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sabrina Rahman Mim",
                "email" => "s.r.m.0850@gmail.coml",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Team lead , Web Development",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mijanur Rahaman",
                "email" => "riponcse.it@bubt.edu.bd",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Asst. Professor",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Saikh Ibne Abu Zafar Newton",
                "email" => "msiazn@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Apps Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Momotaz Rahman",
                "email" => "momo29intk@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Software Engineer ( React JS)",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mehedi Hassan",
                "email" => "mehedi370536@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Managing Director",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Nishat Jahan",
                "email" => "nishatbubt3@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Army Welfare Trust group of Astha Life Insurance company Limited. Position :- FA ( Finance Assosiation )",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Zahidul Islam",
                "email" => "zahidul989@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Junior Instructor (tech) computer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md Rajib Bhuiyan",
                "email" => "mdrajibbhuiyan77@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Digital Marketing Specialist",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Forhadul Islam",
                "email" => "fitareq@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Android Developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Abdullah Al Amin",
                "email" => "ab.alaminshaon@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sudhananda Biswas",
                "email" => "shbsovon@outlook.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => ".net developer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Farzana Reza",
                "email" => "farzana.eva021@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Mallik Mohammed Ashraf",
                "email" => "mallik.ashraf.cse@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Software Engineer",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Md. Sadman Shabir",
                "email" => "shabirsad89@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Accounts and Communication",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ],
            [
                "name" => "Sadman Bin Hasan",
                "email" => "sadmancse0047@gmail.com",
                "type" => \App\Enums\UserType::MEMBER,
                "designation" => "Jr dba",
                "gender" => \App\Enums\GenderEnum::NOT_SHARING,
                "password" => bcrypt(self::DEFAULT_PASSWORD),
            ]
        ]);
    }
}
